### ISSUE TITLE
Set timer doesn't work

### ISSUE THREAD

**Issue by saooms** [Dark-Void-Entertainment-Studios/DDM_prutsers#13]
Steps:

1. log-in
2. Press "start game"
3. set timer to anything other than 3 minutes
4. the timer in the game always displays to have 3 minutes

Expectation
the timer in game changes according to the time you put in at the start

Result
the timer in game always displays 3 minutes

Lenovo laptop | windows 10 | version 0.3.1
Stijn Ooms
21-11-2019

**Comment by Ian-Storm** [comment]
Changed the order in the saving of the setting. This way the timer that you selected works again.
