### ISSUE TITLE
you can play without selecting a character 

### ISSUE THREAD

**Issue by saooms** [Dark-Void-Entertainment-Studios/DDM_prutsers#14]
Steps:

1. log-in
2. Press "start game"
3. continue to character selection
4. proceed without selecting a character
5. game start with character code 0

Expectation
game starts with character 1

Result
game starts with character 0

Lenovo laptop | windows 10 | version 0.3.1
Stijn Ooms
21-11-2019

**Comment by Ian-Storm** [comment]
This is fixed by setting a standard value. This way you alsways play with the standard character.
