### ISSUE TITLE
Admin can't  view admin page

### ISSUE THREAD

**Issue by MerijnWM** [Dark-Void-Entertainment-Studios/DDM_prutsers#15]
Steps:

1. Log-in as admin
2. There is no admin page

Expectation
Under the dropdown of your name should be a link to the admin page 

Result
There is no admin page

bto notebook laptop | windows 10 | version 0.3.1
Merijn Zuurmonnd
21-11-2019

**Comment by Ian-Storm** [comment]
This is fixed by changing the rights and link.
